# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
arr = np.random.randn(1, 2)
print(arr.size * arr.itemsize)

16


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
# ! python -c "import numpy as np; np.info(np.matmul)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
arr = np.zeros(10)
arr[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
np.arange(50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random((3, 3, 3))

array([[[0.2465917 , 0.90252611, 0.82361172],
        [0.74423663, 0.90990665, 0.41990892],
        [0.75581446, 0.36777648, 0.44816574]],

       [[0.12500135, 0.26289203, 0.39305613],
        [0.6834317 , 0.71121839, 0.18845436],
        [0.65378999, 0.84085586, 0.8212149 ]],

       [[0.76490795, 0.52288525, 0.44894687],
        [0.71311471, 0.0228092 , 0.34799834],
        [0.77203029, 0.47147396, 0.64014987]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
arr = np.random.random((10, 10))
mi, ma = arr.min(), arr.max()

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
arr = np.random.random(30)
arr.mean()

0.49997149336575325

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
np.pad(np.ones((5, 5)), pad_width=1, constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr = np.ones((5, 5))
arr[:, [0, -1]] = 0
arr[[0, -1], :] = 0
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [20]:
np.diag(1 + np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [21]:
np.diag(1 + np.arange(4), k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [22]:
arr = np.zeros((8, 8))
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [23]:
np.unravel_index(99, (6, 7, 8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [24]:
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [25]:
arr = np.random.random((5, 5))
(arr - np.mean(arr)) / np.std(arr)

array([[-0.15410897,  1.50151369, -1.50228839,  0.82435423,  0.05287974],
       [-1.23495931, -1.63208642,  0.19223423,  0.40797643,  0.98601356],
       [ 0.33590789,  1.32046537, -0.38420579,  0.41252488, -0.31283385],
       [-1.20123139, -1.55687529,  0.36227501,  0.76548034, -1.5837217 ],
       [ 1.37211543,  0.29275971,  1.02453549,  0.85412423, -1.14284914]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [26]:
color = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

d:\programdata\python36\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [27]:
np.dot(np.zeros((5, 3)), np.zeros((3, 2)))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
np.ones((5, 3)) @ np.ones((3, 2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
arr = np.arange(16)
arr[(arr > 3) & (arr < 8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5), -1))

print(np.sum(range(5), -1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [31]:
z = np.array([1, 2, 3])

In [32]:
z**z

array([ 1,  4, 27], dtype=int32)

In [33]:
2 << z >> 2

array([1, 2, 4], dtype=int32)

In [34]:
z < -z

array([False, False, False])

In [35]:
1j * z

array([0.+1.j, 0.+2.j, 0.+3.j])

In [36]:
z / 1 / 1

array([1., 2., 3.])

In [37]:
z < z

array([False, False, False])

In [38]:
z < z > z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [39]:
print(np.array(0) / np.array(0))

nan


d:\programdata\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [40]:
np.array(0) // np.array(0)

d:\programdata\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [41]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

In [42]:
np.array([np.nan]).astype(float).astype(int)

array([-2147483648])

#### 29. How to round away from zero a float array ? (★☆☆)

In [43]:
z = np.random.uniform(-10, 10, 10)
print(z)

[-8.72902363  7.47709033  7.65940493  8.86535662 -6.52605002 -4.86112574
  7.56896694  3.51092632  6.58143925  5.49538707]


In [44]:
np.copysign(np.ceil(np.abs(z)), z)

array([-9.,  8.,  8.,  9., -7., -5.,  8.,  4.,  7.,  6.])

In [45]:
# or
np.where(z > 0, np.ceil(z), np.floor(z))

array([-9.,  8.,  8.,  9., -7., -5.,  8.,  4.,  7.,  6.])

#### 30. How to find common values between two arrays? (★☆☆)

In [46]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
np.intersect1d(Z1, Z2)

array([0, 1, 4, 6, 8])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [47]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [48]:
# 正常
_ = np.seterr(**defaults)
Z = np.ones(1) / 0

d:\programdata\python36\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [49]:
# or
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [50]:
np.sqrt(-1) == np.emath.sqrt(-1)

d:\programdata\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [51]:
np.datetime64("today") - np.timedelta64(1)

numpy.datetime64('2021-01-16')

In [52]:
np.datetime64("today")

numpy.datetime64('2021-01-17')

In [53]:
np.datetime64("today") + np.timedelta64(1)

numpy.datetime64('2021-01-18')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [54]:
np.arange("2020-09", "2020-10", dtype="datetime64[D]")

array(['2020-09-01', '2020-09-02', '2020-09-03', '2020-09-04',
       '2020-09-05', '2020-09-06', '2020-09-07', '2020-09-08',
       '2020-09-09', '2020-09-10', '2020-09-11', '2020-09-12',
       '2020-09-13', '2020-09-14', '2020-09-15', '2020-09-16',
       '2020-09-17', '2020-09-18', '2020-09-19', '2020-09-20',
       '2020-09-21', '2020-09-22', '2020-09-23', '2020-09-24',
       '2020-09-25', '2020-09-26', '2020-09-27', '2020-09-28',
       '2020-09-29', '2020-09-30'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [55]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3

np.add(A, B, out=B)
np.divide(A, -2, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

In [56]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [57]:
z = np.random.uniform(0, 10, 10)

In [58]:
print(z - z % 1)
print(z // 1)
print(z.astype(int).astype(float))
print(np.trunc(z))
print(np.floor(z))

[9. 6. 3. 8. 0. 1. 7. 3. 0. 1.]
[9. 6. 3. 8. 0. 1. 7. 3. 0. 1.]
[9. 6. 3. 8. 0. 1. 7. 3. 0. 1.]
[9. 6. 3. 8. 0. 1. 7. 3. 0. 1.]
[9. 6. 3. 8. 0. 1. 7. 3. 0. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [59]:
np.zeros((5, 5)) + np.arange(5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [60]:
def generate():
    for x in range(10):
        yield x


np.fromiter(generate(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
np.fromiter((i for i in range(10)), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [62]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [63]:
z = np.random.randn(10)
z.sort()
print(z)

[-0.79406532 -0.37647113 -0.36177111 -0.34360987 -0.13057031 -0.04427678
  0.6470954   0.84758333  1.27865325  1.37968667]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [64]:
%%timeit
np.add.reduce(np.arange(100))

2.09 µs ± 88.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [65]:
%%timeit
np.sum(np.arange(100))

4.58 µs ± 48.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [66]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

tolerance = np.allclose(A, B)
exact = np.array_equal(A, B)

print(tolerance)
print(exact)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [67]:
z = np.zeros(10, dtype=int)
z.flags.writeable = False
z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [68]:
z = np.random.random((10, 2))
X, Y = z[:, 0], z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

print(np.vstack((R, T)))

print(np.concatenate((R[np.newaxis, :], T[np.newaxis, :]), axis=0))

[0.55632717 0.46561342 0.95617445 1.13319766 0.78258454 0.99905353
 0.59243803 0.95043166 0.27484713 0.72810401]
[1.55742988 0.31120461 1.23133211 0.87815757 1.52665729 0.15692043
 0.22064487 1.34785416 0.28146762 0.69504032]
[[0.55632717 0.46561342 0.95617445 1.13319766 0.78258454 0.99905353
  0.59243803 0.95043166 0.27484713 0.72810401]
 [1.55742988 0.31120461 1.23133211 0.87815757 1.52665729 0.15692043
  0.22064487 1.34785416 0.28146762 0.69504032]]
[[0.55632717 0.46561342 0.95617445 1.13319766 0.78258454 0.99905353
  0.59243803 0.95043166 0.27484713 0.72810401]
 [1.55742988 0.31120461 1.23133211 0.87815757 1.52665729 0.15692043
  0.22064487 1.34785416 0.28146762 0.69504032]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [69]:
z = np.random.randint(0, 10, 10)
z[z.argmax()] = 0
print(z)

[5 0 6 6 5 6 8 3 1 4]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [70]:
z = np.zeros((5, 5), [("x", float), ("y", float)])
z["x"], z["y"] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [71]:
x = np.arange(8)
y = x + 0.5
1.0 / np.subtract.outer(x, y)

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

In [72]:
np.linalg.det(1.0 / np.subtract.outer(x, y))

3638.163637117973

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [73]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [74]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [75]:
np.set_printoptions(threshold=float("inf"))
print(np.random.randn(5, 5))

[[ 0.43395835 -1.45222792  1.77422412 -1.54364396 -0.13293386]
 [ 0.72868926  0.4531494   0.16986104 -1.23304036  0.43038014]
 [-0.64025636  0.0174167   0.69500641  0.4859137   0.33839369]
 [-0.67882175  0.12019913 -0.01020891  0.74681551 -0.17381191]
 [ 0.73217088 -0.58819804 -1.17116773 -1.58480374  0.49170146]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [76]:
z = np.arange(10)
v = np.random.uniform(0, 10)
print((np.abs(z - v).argmin()))

0


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [77]:
Z = np.zeros(
    10,
    [
        ("position", [("x", float, 1), ("y", float, 1)]),
        ("color", [("r", float, 1), ("g", float, 1), ("b", float, 1)]),
    ],
)
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


d:\programdata\python36\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [78]:
z = np.random.random((10, 2))
x, y = np.atleast_2d(z[:, 0], z[:, 1])
np.sqrt((x - x.T)**2 + (y - y.T)**2)

array([[0.        , 0.73771372, 0.5184579 , 0.51878861, 0.47725185,
        0.91000828, 0.49360477, 0.29783151, 0.19894075, 0.75066328],
       [0.73771372, 0.        , 0.53887433, 0.92419456, 0.41105259,
        0.38195666, 0.29202233, 0.54475839, 0.62749139, 0.3867084 ],
       [0.5184579 , 0.53887433, 0.        , 0.40653382, 0.62737045,
        0.47709323, 0.52294319, 0.22551089, 0.57611583, 0.29520244],
       [0.51878861, 0.92419456, 0.40653382, 0.        , 0.88023683,
        0.87149355, 0.8208156 , 0.41436737, 0.68769124, 0.6916954 ],
       [0.47725185, 0.41105259, 0.62737045, 0.88023683, 0.        ,
        0.74760469, 0.13461465, 0.47409086, 0.29552303, 0.66780409],
       [0.91000828, 0.38195666, 0.47709323, 0.87149355, 0.74760469,
        0.        , 0.61345838, 0.62925897, 0.87511764, 0.18193133],
       [0.49360477, 0.29202233, 0.52294319, 0.8208156 , 0.13461465,
        0.61345838, 0.        , 0.40645325, 0.34805682, 0.53524188],
       [0.29783151, 0.54475839, 0.2255108

In [80]:
import scipy

scipy.spatial.distance.cdist(z, z, metric="euclidean")

array([[0.        , 0.73771372, 0.5184579 , 0.51878861, 0.47725185,
        0.91000828, 0.49360477, 0.29783151, 0.19894075, 0.75066328],
       [0.73771372, 0.        , 0.53887433, 0.92419456, 0.41105259,
        0.38195666, 0.29202233, 0.54475839, 0.62749139, 0.3867084 ],
       [0.5184579 , 0.53887433, 0.        , 0.40653382, 0.62737045,
        0.47709323, 0.52294319, 0.22551089, 0.57611583, 0.29520244],
       [0.51878861, 0.92419456, 0.40653382, 0.        , 0.88023683,
        0.87149355, 0.8208156 , 0.41436737, 0.68769124, 0.6916954 ],
       [0.47725185, 0.41105259, 0.62737045, 0.88023683, 0.        ,
        0.74760469, 0.13461465, 0.47409086, 0.29552303, 0.66780409],
       [0.91000828, 0.38195666, 0.47709323, 0.87149355, 0.74760469,
        0.        , 0.61345838, 0.62925897, 0.87511764, 0.18193133],
       [0.49360477, 0.29202233, 0.52294319, 0.8208156 , 0.13461465,
        0.61345838, 0.        , 0.40645325, 0.34805682, 0.53524188],
       [0.29783151, 0.54475839, 0.2255108

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [86]:
z = (np.random.rand(10) * 10000).astype(np.float32)
print(z)

y = z.view(np.int32, type=type(z))
y[:] = z
print(y)

[5743.1587 9128.959  5413.611  8200.658  4195.599  7516.528   843.2891
 8104.2827 1215.9498 3682.4722]
[5743 9128 5413 8200 4195 7516  843 8104 1215 3682]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [88]:
from io import StringIO

s = StringIO("""1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
            """)
z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [89]:
z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [91]:
for idx in np.ndindex(z.shape):
    print(idx, z[idx])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [92]:
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(x * x + y * y)
sigma, mu = 1.0, 0.0
g = np.exp(-((D - mu)**2 / (2 * sigma**2)))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [96]:
z = np.zeros((10, 10))
np.put(z, np.random.choice(range(10 * 10), 20, replace=False), 1)
print(z)

[[1. 1. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [97]:
z = np.random.rand(5, 10)
print(z)
z -= z.mean(axis=1, keepdims=True)
print(z)

[[0.06817891 0.36785774 0.98794766 0.36797614 0.02534362 0.30755075
  0.08750639 0.52150229 0.71778408 0.02371964]
 [0.83196475 0.84426568 0.29926043 0.27370629 0.62280282 0.38217743
  0.90964257 0.57825694 0.7325788  0.92310839]
 [0.91549932 0.74203787 0.8336881  0.77378759 0.32699015 0.18258766
  0.51151619 0.84931221 0.42653961 0.65663395]
 [0.54345018 0.16575324 0.58372338 0.82182696 0.59262925 0.03595183
  0.23439327 0.12770884 0.56962655 0.91851014]
 [0.59349399 0.75657278 0.23603692 0.19451442 0.03396893 0.88419196
  0.35098615 0.44024221 0.86849935 0.29588152]]
[[-0.27935781  0.02032101  0.64041094  0.02043942 -0.3221931  -0.03998597
  -0.26003034  0.17396557  0.37024736 -0.32381709]
 [ 0.19218834  0.20448927 -0.34051598 -0.36607012 -0.01697359 -0.25759898
   0.26986616 -0.06151947  0.09280239  0.28333198]
 [ 0.29364006  0.1201786   0.21182884  0.15192832 -0.29486912 -0.4392716
  -0.11034307  0.22745295 -0.19531966  0.03477468]
 [ 0.08409282 -0.29360412  0.12436602  0.3624696  

#### 59. How to sort an array by the nth column? (★★☆)

In [100]:
z = np.random.randint(0, 10, (3, 3))
z[z[:, 1].argsort()]

array([[0, 0, 0],
       [9, 3, 8],
       [2, 4, 1]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [102]:
z = np.random.randint(0, 10, (3, 3))

(~z.any(axis=0)).any()

False

#### 61. Find the nearest value from a given value in an array (★★☆)

In [106]:
z = np.random.randint(0, 10, (3, 3))
print(z)
v = 5
z.flat[np.abs(z - v).argmin()]

[[7 8 2]
 [8 7 0]
 [5 4 5]]


5

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [31]:
a = np.arange(3).reshape(3, 1)
b = np.arange(3).reshape(1, 3)

it = np.nditer([a, b, None])
for x, y, z in it:
    z[...] = x + y

In [33]:
it.operands[2]

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

#### 63. Create an array class that has a name attribute (★★☆)

In [34]:
class NamedArray(np.ndarray):

    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.info = getattr(obj, "name", "no name")

In [35]:
z = NamedArray(np.arange(10), "range_10")
print(z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [41]:
z = np.ones(10)
i = np.random.randint(0, len(z), 20)  # i中数字出现一次，z中index对应加一

print(z)
print(i)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 4 3 5 1 2 4 2 9 7 0 3 3 4 1 1 1 0 0 3]


In [42]:
z + np.bincount(i, minlength=len(z))

array([4., 5., 3., 6., 4., 2., 1., 2., 1., 2.])

In [43]:
np.add.at(z, i, 1)
print(z)

[4. 5. 3. 6. 4. 2. 1. 2. 1. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [44]:
x = [1, 2, 3, 4, 5]  # weight
i = [1, 3, 9, 3, 4]  # 长度为9的bin array计数的对象，注意乘上weight

np.bincount(i, x)

array([0., 1., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [45]:
w, h = 16, 16
I = np.random.randint(0, 256, (h, w, 3)).astype(np.ubyte)
F = I[..., 0] * 256 * 256 + I[..., 1] * 256 + I[..., 2]

print(np.unique(I))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 108 109 110 111 112
 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148
 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166
 167 168 169 170 171 172 173 174 176 177 178 179 180 181 182 183 184 185
 186 187 188 189 190 191 192 193 194 196 197 198 199 200 201 202 203 204
 205 206 207 208 209 210 211 212 213 214 215 217 218 219 220 221 222 223
 224 225 226 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 250 251 252 253 254 25

In [46]:
F = I[..., 0] << 16 + I[..., 1] << 8 + I[..., 2]

print(np.unique(I))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  43  44  45  46  47  48  49  50  51  52  53  54  55
  56  57  58  59  60  61  62  63  65  66  67  68  69  70  71  72  73  74
  75  76  77  78  79  80  81  82  83  84  85  86  87  88  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 104 105 106 108 109 110 111 112
 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148
 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166
 167 168 169 170 171 172 173 174 176 177 178 179 180 181 182 183 184 185
 186 187 188 189 190 191 192 193 194 196 197 198 199 200 201 202 203 204
 205 206 207 208 209 210 211 212 213 214 215 217 218 219 220 221 222 223
 224 225 226 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 250 251 252 253 254 25

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [49]:
A = np.random.randint(0, 10, (3, 4, 3, 4))

A.sum(axis=(-2, -1))
print(A)

[[[[0 6 2 8]
   [3 0 0 8]
   [7 4 7 3]]

  [[8 7 4 7]
   [6 7 9 8]
   [8 8 9 9]]

  [[6 7 9 0]
   [0 5 8 9]
   [9 8 0 1]]

  [[4 6 0 2]
   [4 5 8 6]
   [8 9 6 8]]]


 [[[9 4 5 2]
   [6 1 6 6]
   [3 1 0 0]]

  [[8 4 2 6]
   [7 0 0 7]
   [1 5 5 8]]

  [[1 4 9 3]
   [2 1 5 2]
   [5 2 3 0]]

  [[3 7 6 6]
   [8 2 9 8]
   [8 3 4 1]]]


 [[[5 0 2 3]
   [5 3 4 4]
   [9 5 5 2]]

  [[0 2 0 3]
   [6 4 8 5]
   [5 2 8 6]]

  [[8 5 1 5]
   [1 7 1 2]
   [9 5 6 6]]

  [[2 5 3 6]
   [9 5 8 7]
   [8 5 0 7]]]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [50]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)  # 根据S中的不同值，分组对D中对应index元素求和
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.49011505 0.41078074 0.48585995 0.46265258 0.36967635 0.52376235
 0.33658622 0.52229719 0.35699286 0.49113063]


In [53]:
S

array([3, 2, 6, 9, 4, 9, 1, 5, 9, 8, 6, 6, 1, 0, 2, 7, 6, 6, 3, 5, 5, 9,
       3, 8, 6, 0, 0, 5, 4, 7, 0, 4, 0, 7, 8, 9, 7, 8, 4, 4, 7, 3, 0, 0,
       3, 6, 9, 2, 1, 0, 0, 1, 1, 9, 7, 0, 6, 1, 1, 2, 5, 3, 5, 0, 9, 6,
       5, 6, 2, 4, 0, 6, 7, 9, 5, 7, 2, 8, 9, 9, 7, 0, 8, 8, 9, 1, 0, 3,
       7, 0, 2, 6, 2, 6, 7, 2, 6, 9, 4, 7])

In [54]:
np.bincount(S, weights=None)

array([15,  8,  9,  7,  7,  8, 14, 12,  7, 13], dtype=int64)

In [55]:
# pandas 方式
import pandas as pd

print(pd.Series(D).groupby(S).mean())

0    0.490115
1    0.410781
2    0.485860
3    0.462653
4    0.369676
5    0.523762
6    0.336586
7    0.522297
8    0.356993
9    0.491131
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [56]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))

# slower
np.diag(np.dot(A, B))

array([0.67498024, 1.25507745, 1.06745788, 0.92332666, 1.62831896])

In [57]:
# faster
np.sum(A * B.T, axis=1)

array([0.67498024, 1.25507745, 1.06745788, 0.92332666, 1.62831896])

In [58]:
# and more
np.einsum("ij,ji->i", A, B)

array([0.67498024, 1.25507745, 1.06745788, 0.92332666, 1.62831896])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [60]:
Z = np.array([1, 2, 3, 4, 5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z) - 1) * (nz))

Z0[::nz + 1] = Z
Z0

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [61]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))

A * B[:, :, None]

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

#### 72. How to swap two rows of an array? (★★★)

In [62]:
A = np.arange(25).reshape(5, 5)

A[[0, 1]] = A[[1, 0]]

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [63]:
faces = np.random.randint(0, 100, (10, 3))

In [64]:
faces

array([[93, 37, 24],
       [86, 19, 76],
       [86, 70, 64],
       [65, 10, 68],
       [52, 46,  1],
       [89, 48, 61],
       [41, 92, 38],
       [42, 89, 17],
       [57, 24, 85],
       [35, 64, 99]])

In [65]:
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)

In [66]:
F

array([[93, 37, 37, 24, 24, 93],
       [86, 19, 19, 76, 76, 86],
       [86, 70, 70, 64, 64, 86],
       [65, 10, 10, 68, 68, 65],
       [52, 46, 46,  1,  1, 52],
       [89, 48, 48, 61, 61, 89],
       [41, 92, 92, 38, 38, 41],
       [42, 89, 89, 17, 17, 42],
       [57, 24, 24, 85, 85, 57],
       [35, 64, 64, 99, 99, 35]])

In [67]:
F = F.reshape(len(F) * 3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[("p0", F.dtype), ("p1", F.dtype)])
G = np.unique(G)

In [68]:
G

array([( 1, 46), ( 1, 52), (10, 65), (10, 68), (17, 42), (17, 89),
       (19, 76), (19, 86), (24, 37), (24, 57), (24, 85), (24, 93),
       (35, 64), (35, 99), (37, 93), (38, 41), (38, 92), (41, 92),
       (42, 89), (46, 52), (48, 61), (48, 89), (57, 85), (61, 89),
       (64, 70), (64, 86), (64, 99), (65, 68), (70, 86), (76, 86)],
      dtype=[('p0', '<i4'), ('p1', '<i4')])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [69]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])

A = np.repeat(np.arange(len(C)), C)

print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [70]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

In [71]:
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [7]:
from numpy.lib import stride_tricks


def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)  # itemsize:单个数据占用内存大小
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

In [9]:
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [10]:
Z = np.random.randint(0, 2, 100)
np.logical_not(Z, out=Z)

array([0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1])

In [12]:
Z = np.random.uniform(-1.0, 1.0, 10)
np.negative(Z, out=Z)

array([ 0.21777839,  0.37126693,  0.13784339, -0.32770525,  0.11819709,
        0.48808794, -0.01875944, -0.65925857, -0.91935906,  0.8204897 ])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [23]:
def distance(P0, P1, p):
    "两点式计算直线方程"
    A = 1 / (P1[:, 0] - P0[:, 0])
    B = 1 / (P0[:, 1] - P1[:, 1])
    demo = np.sqrt(A**2 + B**2)
    nume = np.abs((p[..., 0] - P0[:, 0]) / (P1[:, 0] - P0[:, 0]) -
                  (p[..., 1] - P0[:, 1]) / (P1[:, 1] - P0[:, 1]))
    return nume / demo

In [24]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))
print(distance(P0, P1, p))

[ 1.34016498  2.94699675  1.33216781 13.30918772  1.46169351  8.34145029
  8.25495435 10.80120229  9.8403334   0.25548123]


In [25]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:, 0] - p[..., 0]) * T[:, 0] +
          (P0[:, 1] - p[..., 1]) * T[:, 1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))


# P0 = np.random.uniform(-10,10,(10,2))
# P1 = np.random.uniform(-10,10,(10,2))
# p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.34016498  2.94699675  1.33216781 13.30918772  1.46169351  8.34145029
  8.25495435 10.80120229  9.8403334   0.25548123]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [26]:
P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(np.array([distance(P0, P1, p_i) for p_i in p]))

[[ 9.97382774  4.09155788  0.67674642  7.64048427  9.48071972  7.20184173
   1.21140316  3.8583378   3.99043747  1.64545168]
 [13.14762037  4.05519109  4.22169328  7.94119073 10.08665032  8.42911276
   3.59543973  1.07871678  7.50266679  4.87573071]
 [ 9.46369504  7.52084242  1.55575668 10.84231371 12.4496922   9.61333598
   2.83275603  7.74839803  2.20927464  0.98489695]
 [10.6401713   8.80059043  7.67883169  4.52874915  1.93268825  2.35885196
  15.49040974  9.68444942  9.30677391  2.85561486]
 [ 1.27627457  0.59028424  7.28900811  3.39774552  4.59486272  1.09457949
   1.47110329  7.85388389  4.35486642  7.05822743]
 [11.20219051  0.09858122  4.07701058  3.79217389  5.97474549  4.494558
   6.59991423  1.41773886  6.83388876  3.06809284]
 [13.17131808  7.68802527  2.48361663 11.39265318 13.34533778 11.20680519
   0.27193937  4.71212797  6.23774733  4.74985091]
 [ 9.94300447  4.35960257  0.51230478  7.89170624  9.71460561  7.39391117
   0.90198523  4.15457618  3.86119435  1.60302771]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [27]:
# 这是不是太麻烦了
Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill = 0
position = (1, 1)

R = np.ones(shape, dtype=Z.dtype) * fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = P - Rs // 2
Z_stop = (P + Rs // 2) + Rs % 2

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop - Zs, 0))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

r = [slice(start, stop) for start, stop in zip(R_start, R_stop)]
z = [slice(start, stop) for start, stop in zip(Z_start, Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[6 7 2 3 1 5 0 4 6 9]
 [5 5 1 5 6 0 5 5 5 2]
 [8 9 0 8 5 6 2 4 3 3]
 [8 0 6 5 2 9 4 8 9 0]
 [2 7 2 8 8 2 8 9 4 2]
 [0 7 4 7 0 9 4 4 9 8]
 [6 2 1 6 9 4 8 0 0 1]
 [6 0 4 3 8 2 3 3 5 3]
 [0 8 2 5 7 1 6 2 0 3]
 [2 8 9 8 3 4 3 2 6 7]]
[[0 0 0 0 0]
 [0 6 7 2 3]
 [0 5 5 1 5]
 [0 8 9 0 8]
 [0 8 0 6 5]]


d:\programdata\python36\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [28]:
Z = np.arange(1, 15, dtype=np.uint32)
R = stride_tricks.as_strided(Z, shape=(11, 4), strides=(4, 4))
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★)

In [30]:
Z = np.random.uniform(0, 1, (10, 10))

U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)

print(rank)

10


#### 83. How to find the most frequent value in an array?

In [31]:
Z = np.random.randint(0, 10, 50)

np.bincount(Z).argmax()

0

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [34]:
# strides: 跨越数组各个维度所需要经过的字节数（bytes）
Z.strides + Z.strides

(40, 4, 40, 4)

In [35]:
Z

array([[3, 4, 2, 0, 1, 3, 0, 0, 1, 4],
       [3, 0, 1, 2, 4, 0, 4, 1, 4, 2],
       [0, 2, 0, 1, 2, 4, 4, 1, 4, 2],
       [4, 0, 3, 4, 1, 3, 3, 4, 3, 2],
       [3, 0, 2, 4, 4, 1, 4, 0, 0, 0],
       [2, 3, 2, 1, 0, 4, 4, 3, 4, 1],
       [3, 0, 3, 4, 3, 3, 4, 2, 1, 1],
       [1, 4, 3, 4, 4, 2, 1, 4, 1, 0],
       [3, 0, 0, 3, 4, 3, 3, 2, 3, 0],
       [4, 0, 1, 0, 2, 4, 0, 2, 1, 2]])

In [32]:
Z = np.random.randint(0, 5, (10, 10))
n = 3
i = 1 + (Z.shape[0] - 3)
j = 1 + (Z.shape[1] - 3)
# strides： 四个维度，每个维度index加一，stride的变化
C = stride_tricks.as_strided(Z,
                             shape=(i, j, n, n),
                             strides=Z.strides + Z.strides)
print(C)

[[[[3 4 2]
   [3 0 1]
   [0 2 0]]

  [[4 2 0]
   [0 1 2]
   [2 0 1]]

  [[2 0 1]
   [1 2 4]
   [0 1 2]]

  [[0 1 3]
   [2 4 0]
   [1 2 4]]

  [[1 3 0]
   [4 0 4]
   [2 4 4]]

  [[3 0 0]
   [0 4 1]
   [4 4 1]]

  [[0 0 1]
   [4 1 4]
   [4 1 4]]

  [[0 1 4]
   [1 4 2]
   [1 4 2]]]


 [[[3 0 1]
   [0 2 0]
   [4 0 3]]

  [[0 1 2]
   [2 0 1]
   [0 3 4]]

  [[1 2 4]
   [0 1 2]
   [3 4 1]]

  [[2 4 0]
   [1 2 4]
   [4 1 3]]

  [[4 0 4]
   [2 4 4]
   [1 3 3]]

  [[0 4 1]
   [4 4 1]
   [3 3 4]]

  [[4 1 4]
   [4 1 4]
   [3 4 3]]

  [[1 4 2]
   [1 4 2]
   [4 3 2]]]


 [[[0 2 0]
   [4 0 3]
   [3 0 2]]

  [[2 0 1]
   [0 3 4]
   [0 2 4]]

  [[0 1 2]
   [3 4 1]
   [2 4 4]]

  [[1 2 4]
   [4 1 3]
   [4 4 1]]

  [[2 4 4]
   [1 3 3]
   [4 1 4]]

  [[4 4 1]
   [3 3 4]
   [1 4 0]]

  [[4 1 4]
   [3 4 3]
   [4 0 0]]

  [[1 4 2]
   [4 3 2]
   [0 0 0]]]


 [[[4 0 3]
   [3 0 2]
   [2 3 2]]

  [[0 3 4]
   [0 2 4]
   [3 2 1]]

  [[3 4 1]
   [2 4 4]
   [2 1 0]]

  [[4 1 3]
   [4 4 1]
   [1 0 4]]

  [[1 3 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [36]:
class Symetric(np.ndarray):

    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)

In [39]:
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

In [40]:
S = symetric(np.random.randint(0, 10, (5, 5)))
S

Symetric([[ 5,  6, 13, 13, 12],
          [ 6,  7,  6,  6, 13],
          [13,  6,  6,  2,  9],
          [13,  6,  2,  3, 10],
          [12, 13,  9, 10,  4]])

In [41]:
S[3, 4] = 0
S

Symetric([[ 5,  6, 13, 13, 12],
          [ 6,  7,  6,  6, 13],
          [13,  6,  6,  2,  9],
          [13,  6,  2,  3,  0],
          [12, 13,  9,  0,  4]])

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of the p matrix products at once? (result has shape (n,1)) (★★★)

In [42]:
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))

# axes指定 M，V 中的轴进行 sum reduction，输出 shape 为 余下的轴 组成的shape
S = np.tensordot(M, V, axes=[(0, 2), (0, 1)])

S

array([[200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.],
       [200.]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [43]:
Z = np.ones((16, 16))
k = 4

# 横向 k 步求和，纵向 k 步求和
S = np.add.reduceat(
    np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
    np.arange(0, Z.shape[1], k),
    axis=1,
)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [45]:
# 搜索 game of life 问题


def iterate(Z):
    # Count neighbours
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] + Z[1:-1, 0:-2] +
         Z[1:-1, 2:] + Z[2:, 0:-2] + Z[2:, 1:-1] + Z[2:, 2:])

    # Apply rules
    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z


Z = np.random.randint(0, 2, (10, 10))
for i in range(100):
    Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [46]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

In [47]:
# Slow
print(Z[np.argsort(Z)[-n:]])

# Fast
print(Z[np.argpartition(-Z, n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9995 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [54]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    # index组合
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    # 根据index，从各个array中读取相应数值
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix


print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [55]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])

# string, float, int
R = np.core.records.fromarrays(Z.T,
                               names="col1, col2, col3",
                               formats="S8, f8, i8")

print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [56]:
x = np.random.rand(int(5e7))

In [57]:
x

array([0.19177447, 0.07078996, 0.59925443, ..., 0.07156629, 0.99472137,
       0.59774015])

In [58]:
%timeit np.power(x,3)

1.95 s ± 65.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [59]:
%timeit x**3

1.97 s ± 49.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [60]:
%timeit np.einsum('i,i,i->i',x,x,x)

202 ms ± 8.88 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [61]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

# A中的每一个元素与B进行比较
C = A[..., np.newaxis, np.newaxis] == B

In [69]:
# C

In [72]:
# 1轴为A中每个单独值，有三行； 3轴为A中每个值与B比较的的结果
# 即任意一行A中的元素，是否包含来自B中所有不同行的值
C.any((3, 1)).all(1)

array([False,  True,  True,  True,  True,  True, False,  True])

In [73]:
rows = np.where(C.any((3, 1)).all(1))[0]
print(rows)

[1 2 3 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [75]:
Z = np.random.randint(0, 5, (10, 3))

In [76]:
Z[~np.all(Z[:, 1:] == Z[:, :-1], axis=1)]  # 依次比较

array([[4, 3, 3],
       [1, 4, 2],
       [1, 4, 0],
       [3, 4, 1],
       [2, 2, 0],
       [3, 0, 1],
       [1, 4, 2],
       [0, 1, 2],
       [2, 1, 3]])

In [77]:
Z[Z.max(axis=1) != Z.min(axis=1), :]

array([[4, 3, 3],
       [1, 4, 2],
       [1, 4, 0],
       [3, 4, 1],
       [2, 2, 0],
       [3, 0, 1],
       [1, 4, 2],
       [0, 1, 2],
       [2, 1, 3]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [78]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1, 1) & (2**np.arange(8))) != 0).astype(int)
print(B[:, ::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [79]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
np.unpackbits(I[:, np.newaxis], axis=1)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [82]:
Z = np.random.randint(0, 2, (6, 3))
print(Z)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 0]
 [1 1 0]
 [0 0 0]
 [0 0 0]
 [0 1 1]
 [1 1 1]]
[[0 0 0]
 [0 1 0]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [83]:
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)

In [84]:
np.einsum("i->", A)  # np.sum(A)

4.571081724334019

In [85]:
np.einsum("i,i->i", A, B)  # A * B

array([0.07360314, 0.42124468, 0.00260285, 0.14278601, 0.12411123,
       0.10699638, 0.26059924, 0.00500204, 0.4743901 , 0.19404716])

In [86]:
np.einsum("i,i", A, B)  # np.inner(A, B)

1.8053828321198488

In [87]:
np.einsum("i,j->ij", A, B)  # np.outer(A, B)

array([[0.07360314, 0.14008114, 0.08274066, 0.05396978, 0.1540963 ,
        0.06818168, 0.19288853, 0.10491152, 0.21192297, 0.09670005],
       [0.2213355 , 0.42124468, 0.24881338, 0.16229511, 0.46339032,
        0.20503237, 0.58004428, 0.31548444, 0.63728364, 0.29079133],
       [0.0023154 , 0.00440666, 0.00260285, 0.00169778, 0.00484755,
        0.00214485, 0.00606788, 0.0033003 , 0.00666666, 0.00304198],
       [0.1947293 , 0.37060789, 0.21890414, 0.14278601, 0.40768731,
        0.18038594, 0.51031858, 0.27756083, 0.56067734, 0.25583602],
       [0.05928095, 0.11282323, 0.06664044, 0.04346799, 0.12411123,
        0.05491444, 0.15535501, 0.08449715, 0.1706856 , 0.07788352],
       [0.11550418, 0.21982701, 0.12984354, 0.08469389, 0.24182076,
        0.10699638, 0.30269676, 0.16463591, 0.33256719, 0.15174978],
       [0.09944045, 0.18925459, 0.11178557, 0.07291509, 0.20818956,
        0.09211587, 0.26059924, 0.14173919, 0.28631544, 0.1306452 ],
       [0.0035093 , 0.00667888, 0.0039449

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [90]:
phi = np.arange(0, 10 * np.pi, 0.5)
a = 1
x = a * phi * np.cos(phi)
y = a * phi * np.sin(phi)

print(x)
print(y)

[  0.           0.43879128   0.54030231   0.1061058   -0.83229367
  -2.00285904  -2.96997749  -3.27759841  -2.61457448  -0.9485811
   1.41831093   3.89768376   5.76102172   6.34781957   5.27731578
   2.59976488  -1.16400027  -5.11710117  -8.20017236  -9.47313548
  -8.39071529  -4.99313774   0.04868268   5.55800473  10.1262475
  12.47247849  11.79680816   8.03142895   1.91432105  -5.14640187
 -11.39531869 -15.16602867 -15.32255169 -11.58955145  -4.67777675
   3.84019936  11.88570075  17.38121053  18.78538775  15.51839191
   8.16164124  -1.63105313 -11.50231446 -18.95852214 -21.99913818
 -19.6493544  -12.25515947  -1.45477441  10.18029618  19.7570326
  24.7800703   23.79953536  16.81990238   5.35658069  -7.88774784
 -19.65939164 -26.95296426 -27.77739036 -21.69366836  -9.98041672
   4.6275435   18.57620727  28.35701309]
[  0.           0.23971277   0.84147098   1.49624248   1.81859485
   1.49618036   0.42336002  -1.2277413   -3.02720998  -4.39888553
  -4.79462137  -3.88047179  -1.6764929

In [91]:
# 相邻两点距离
dr = (np.diff(x)**2 + np.diff(y)**2)**0.5

In [93]:
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)  # 累计长度和
r

array([  0.        ,   0.5       ,   1.11026014,   1.89591421,
         2.88813627,   4.1022921 ,   5.54668179,   7.22619547,
         9.14392545,  11.30194023,  13.70168703,  16.34421595,
        19.23031209,  22.36057728,  25.73548274,  29.35540415,
        33.22064574,  37.33145729,  41.68804632,  46.29058714,
        51.13922748,  56.23409372,  61.57529473,  67.16292499,
        72.99706699,  79.07779321,  85.40516766,  91.97924712,
        98.80008223, 105.86771832, 113.18219613, 120.7435524 ,
       128.55182041, 136.60703036, 144.90920976, 153.45838374,
       162.2545753 , 171.29780557, 180.588094  , 190.1254585 ,
       199.90991565, 209.94148079, 220.22016817, 230.74599102,
       241.51896166, 252.53909159, 263.80639156, 275.3208716 ,
       287.08254113, 299.09140899, 311.34748347, 323.85077238,
       336.60128307, 349.59902248, 362.84399715, 376.33621326,
       390.07567666, 404.0623929 , 418.29636723, 432.77760463,
       447.50610983, 462.48188733, 477.70494141])

In [96]:
r_int = np.linspace(0, r.max(), 200)  # 均分

x_int = np.interp(r_int, r, x)  # 根据 r, x 插值计算r_int处的值
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [102]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0], [2.0, 0.0, 1.0, 1.0], [1.5, 2.5, 1.0, 0.0]])
n = 4  # 和为4的行

M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
X[M & (X.sum(axis=-1) == n)]

array([[2., 0., 1., 1.]])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [103]:
X = np.random.randn(100)

# sample indexes
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))

means = X[idx].mean(axis=1)

confindence = np.percentile(means, [2.5, 97.5])

print(confindence)

[-0.27451145  0.08839754]
